// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQt2StWQi0X68-sHrMeH4aK7T4LkYyTg',
    appId: '1:996875162319:web:897ca9e1eaecafc4139dba',
    messagingSenderId: '996875162319',
    projectId: 'flutter-challenge-20210610',
    authDomain: 'flutter-challenge-20210610.firebaseapp.com',
    databaseURL: 'https://flutter-challenge-20210610-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-challenge-20210610.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4NZO7Xw9182wBZPYhF1yyfrt-Zwq2aGw',
    appId: '1:996875162319:android:d7dbe85e377ea3b7139dba',
    messagingSenderId: '996875162319',
    projectId: 'flutter-challenge-20210610',
    databaseURL: 'https://flutter-challenge-20210610-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-challenge-20210610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKYzA2noA0tJDuefUmQfRQ8IfmO4IRSfA',
    appId: '1:996875162319:ios:3ad81b3020c6cb6b139dba',
    messagingSenderId: '996875162319',
    projectId: 'flutter-challenge-20210610',
    databaseURL: 'https://flutter-challenge-20210610-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-challenge-20210610.appspot.com',
    iosClientId: '996875162319-8gftoffvmg8mphsqok2ajaeu1oei5r21.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChallenge',
  );
}
